package com.example.jmren.checklistii

enum class kAction {
    CREATE_TASK, COMPLETE_TASK, DELETE_TASK, CHANGE_TASK_NAME,
    CHANGE_TASK_DESCRIPTION, CHANGE_TASK_DEADLINE, REMOVE_TASK_DEADLINE
}